"""tablas_core_y_catalogos

Revision ID: e239c1b54a9e
Revises: 8d22c13dbf16
Create Date: 2025-11-25 21:56:38.342589+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e239c1b54a9e'
down_revision: Union[str, Sequence[str], None] = '8d22c13dbf16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
