"""modelo_completo_final

Revision ID: e570198d1dbd
Revises: e239c1b54a9e
Create Date: 2025-11-25 22:22:26.766632+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e570198d1dbd'
down_revision: Union[str, Sequence[str], None] = 'e239c1b54a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('INV_ESTADO_OPERATIVO',
    sa.Column('EOP_Estado_Operativo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EOP_Nombre', sa.String(length=50), nullable=False),
    sa.Column('EOP_Descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('EOP_Estado_Operativo'),
    sa.UniqueConstraint('EOP_Nombre')
    )
    op.create_index(op.f('ix_INV_ESTADO_OPERATIVO_EOP_Estado_Operativo'), 'INV_ESTADO_OPERATIVO', ['EOP_Estado_Operativo'], unique=False)
    op.create_table('INV_MARCA',
    sa.Column('MAR_Marca', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MAR_Nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('MAR_Marca'),
    sa.UniqueConstraint('MAR_Nombre')
    )
    op.create_index(op.f('ix_INV_MARCA_MAR_Marca'), 'INV_MARCA', ['MAR_Marca'], unique=False)
    op.create_table('INV_SOFTWARE',
    sa.Column('SOF_Software', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SOF_Nombre', sa.String(length=100), nullable=False),
    sa.Column('SOF_Version', sa.String(length=50), nullable=True),
    sa.Column('SOF_Fabricante', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('SOF_Software')
    )
    op.create_index(op.f('ix_INV_SOFTWARE_SOF_Software'), 'INV_SOFTWARE', ['SOF_Software'], unique=False)
    op.create_table('INV_TIPO_ACTIVO',
    sa.Column('TAC_Tipo_Activo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TAC_Nombre', sa.String(length=100), nullable=False),
    sa.Column('TAC_Aplica_Depreciacion', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('TAC_Tipo_Activo'),
    sa.UniqueConstraint('TAC_Nombre')
    )
    op.create_index(op.f('ix_INV_TIPO_ACTIVO_TAC_Tipo_Activo'), 'INV_TIPO_ACTIVO', ['TAC_Tipo_Activo'], unique=False)
    op.create_table('INV_TIPO_CONEXION',
    sa.Column('TCN_Tipo_Conexion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TCN_Nombre', sa.String(length=50), nullable=False),
    sa.Column('TCN_Descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('TCN_Tipo_Conexion'),
    sa.UniqueConstraint('TCN_Nombre')
    )
    op.create_index(op.f('ix_INV_TIPO_CONEXION_TCN_Tipo_Conexion'), 'INV_TIPO_CONEXION', ['TCN_Tipo_Conexion'], unique=False)
    op.create_table('INV_TIPO_ESPECIFICACION',
    sa.Column('TES_Tipo_Especificacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TES_Nombre', sa.String(length=100), nullable=False),
    sa.Column('TES_Unidad_Medida', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('TES_Tipo_Especificacion'),
    sa.UniqueConstraint('TES_Nombre')
    )
    op.create_index(op.f('ix_INV_TIPO_ESPECIFICACION_TES_Tipo_Especificacion'), 'INV_TIPO_ESPECIFICACION', ['TES_Tipo_Especificacion'], unique=False)
    op.create_table('INV_TIPO_EVIDENCIA',
    sa.Column('TEV_Tipo_Evidencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TEV_Nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('TEV_Tipo_Evidencia'),
    sa.UniqueConstraint('TEV_Nombre')
    )
    op.create_index(op.f('ix_INV_TIPO_EVIDENCIA_TEV_Tipo_Evidencia'), 'INV_TIPO_EVIDENCIA', ['TEV_Tipo_Evidencia'], unique=False)
    op.create_table('INV_TIPO_LICENCIA',
    sa.Column('TLI_Tipo_Licencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TLI_Nombre', sa.String(length=50), nullable=False),
    sa.Column('TLI_Descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('TLI_Tipo_Licencia'),
    sa.UniqueConstraint('TLI_Nombre')
    )
    op.create_index(op.f('ix_INV_TIPO_LICENCIA_TLI_Tipo_Licencia'), 'INV_TIPO_LICENCIA', ['TLI_Tipo_Licencia'], unique=False)
    op.create_table('INV_TIPO_MANTENIMIENTO',
    sa.Column('TMA_Tipo_Mantenimiento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TMA_Nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('TMA_Tipo_Mantenimiento'),
    sa.UniqueConstraint('TMA_Nombre')
    )
    op.create_index(op.f('ix_INV_TIPO_MANTENIMIENTO_TMA_Tipo_Mantenimiento'), 'INV_TIPO_MANTENIMIENTO', ['TMA_Tipo_Mantenimiento'], unique=False)
    op.create_table('INV_TIPO_MOVIMIENTO',
    sa.Column('TMO_Tipo_Movimiento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TMO_Nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('TMO_Tipo_Movimiento'),
    sa.UniqueConstraint('TMO_Nombre')
    )
    op.create_index(op.f('ix_INV_TIPO_MOVIMIENTO_TMO_Tipo_Movimiento'), 'INV_TIPO_MOVIMIENTO', ['TMO_Tipo_Movimiento'], unique=False)
    op.create_table('SYS_CONFIGURACION',
    sa.Column('SYS_Configuracion', sa.Integer(), nullable=False),
    sa.Column('SYS_Nombre_Empresa', sa.String(length=100), nullable=True),
    sa.Column('SYS_Logo_URL', sa.String(length=255), nullable=True),
    sa.Column('SYS_Color_Primario', sa.String(length=10), nullable=True),
    sa.Column('SYS_Color_Secundario', sa.String(length=10), nullable=True),
    sa.Column('SYS_Idioma_Defecto', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('SYS_Configuracion')
    )
    op.create_table('INV_LICENCIA',
    sa.Column('LIC_Licencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LIC_Clave_Activacion', sa.String(length=255), nullable=True),
    sa.Column('LIC_Fecha_Vencimiento', sa.Date(), nullable=True),
    sa.Column('LIC_Cantidad_Total', sa.Integer(), nullable=True),
    sa.Column('LIC_Cantidad_Usada', sa.Integer(), nullable=True),
    sa.Column('SOF_Software', sa.Integer(), nullable=False),
    sa.Column('TLI_Tipo_Licencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['SOF_Software'], ['INV_SOFTWARE.SOF_Software'], ),
    sa.ForeignKeyConstraint(['TLI_Tipo_Licencia'], ['INV_TIPO_LICENCIA.TLI_Tipo_Licencia'], ),
    sa.PrimaryKeyConstraint('LIC_Licencia')
    )
    op.create_index(op.f('ix_INV_LICENCIA_LIC_Licencia'), 'INV_LICENCIA', ['LIC_Licencia'], unique=False)
    op.create_table('INV_MODELO',
    sa.Column('MOD_Modelo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MOD_Nombre', sa.String(length=150), nullable=False),
    sa.Column('MOD_Anio_Lanzamiento', sa.Integer(), nullable=True),
    sa.Column('MAR_Marca', sa.Integer(), nullable=False),
    sa.Column('TCN_Tipo_Conexion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['MAR_Marca'], ['INV_MARCA.MAR_Marca'], ),
    sa.ForeignKeyConstraint(['TCN_Tipo_Conexion'], ['INV_TIPO_CONEXION.TCN_Tipo_Conexion'], ),
    sa.PrimaryKeyConstraint('MOD_Modelo')
    )
    op.create_index(op.f('ix_INV_MODELO_MOD_Modelo'), 'INV_MODELO', ['MOD_Modelo'], unique=False)
    op.create_table('INV_ACTIVO',
    sa.Column('ACT_Activo', sa.UUID(), nullable=False),
    sa.Column('ACT_Codigo_Interno', sa.String(length=50), nullable=False),
    sa.Column('ACT_Serie_Fabricante', sa.String(length=100), nullable=False),
    sa.Column('ACT_Hostname', sa.String(length=100), nullable=True),
    sa.Column('ACT_Fecha_Compra', sa.Date(), nullable=False),
    sa.Column('ACT_Fin_Garantia', sa.Date(), nullable=True),
    sa.Column('ACT_Costo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('MOD_Modelo', sa.Integer(), nullable=False),
    sa.Column('TAC_Tipo_Activo', sa.Integer(), nullable=False),
    sa.Column('EOP_Estado_Operativo', sa.Integer(), nullable=False),
    sa.Column('ACT_Activo_Padre', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ACT_Activo_Padre'], ['INV_ACTIVO.ACT_Activo'], ),
    sa.ForeignKeyConstraint(['EOP_Estado_Operativo'], ['INV_ESTADO_OPERATIVO.EOP_Estado_Operativo'], ),
    sa.ForeignKeyConstraint(['MOD_Modelo'], ['INV_MODELO.MOD_Modelo'], ),
    sa.ForeignKeyConstraint(['TAC_Tipo_Activo'], ['INV_TIPO_ACTIVO.TAC_Tipo_Activo'], ),
    sa.PrimaryKeyConstraint('ACT_Activo')
    )
    op.create_index(op.f('ix_INV_ACTIVO_ACT_Activo'), 'INV_ACTIVO', ['ACT_Activo'], unique=False)
    op.create_index(op.f('ix_INV_ACTIVO_ACT_Codigo_Interno'), 'INV_ACTIVO', ['ACT_Codigo_Interno'], unique=True)
    op.create_table('INV_USUARIO',
    sa.Column('USU_Usuario', sa.UUID(), nullable=False),
    sa.Column('USU_Username', sa.String(length=50), nullable=False),
    sa.Column('USU_Password_Hash', sa.String(length=255), nullable=False),
    sa.Column('USU_Salt', sa.String(length=255), nullable=False),
    sa.Column('USU_Ultimo_Login', sa.DateTime(), nullable=True),
    sa.Column('USU_Rol', sa.String(length=20), nullable=False),
    sa.Column('USU_Estado', sa.Boolean(), nullable=True),
    sa.Column('PER_Persona', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['PER_Persona'], ['INV_PERSONA.PER_Persona'], ),
    sa.PrimaryKeyConstraint('USU_Usuario'),
    sa.UniqueConstraint('PER_Persona')
    )
    op.create_index(op.f('ix_INV_USUARIO_USU_Username'), 'INV_USUARIO', ['USU_Username'], unique=True)
    op.create_index(op.f('ix_INV_USUARIO_USU_Usuario'), 'INV_USUARIO', ['USU_Usuario'], unique=False)
    op.create_table('INV_AUDITORIA_SISTEMA',
    sa.Column('AUD_Auditoria', sa.UUID(), nullable=False),
    sa.Column('AUD_Fecha_Hora', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('AUD_Accion', sa.String(length=50), nullable=False),
    sa.Column('AUD_Entidad_Afectada', sa.String(length=50), nullable=False),
    sa.Column('AUD_Snapshot_JSON', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('AUD_IP_Origen', sa.String(length=45), nullable=True),
    sa.Column('USU_Usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['USU_Usuario'], ['INV_USUARIO.USU_Usuario'], ),
    sa.PrimaryKeyConstraint('AUD_Auditoria')
    )
    op.create_index(op.f('ix_INV_AUDITORIA_SISTEMA_AUD_Auditoria'), 'INV_AUDITORIA_SISTEMA', ['AUD_Auditoria'], unique=False)
    op.create_table('INV_ESPECIFICACION',
    sa.Column('ESP_Especificacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ESP_Valor', sa.String(length=255), nullable=False),
    sa.Column('ACT_Activo', sa.UUID(), nullable=False),
    sa.Column('TES_Tipo_Especificacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ACT_Activo'], ['INV_ACTIVO.ACT_Activo'], ),
    sa.ForeignKeyConstraint(['TES_Tipo_Especificacion'], ['INV_TIPO_ESPECIFICACION.TES_Tipo_Especificacion'], ),
    sa.PrimaryKeyConstraint('ESP_Especificacion')
    )
    op.create_index(op.f('ix_INV_ESPECIFICACION_ESP_Especificacion'), 'INV_ESPECIFICACION', ['ESP_Especificacion'], unique=False)
    op.create_table('INV_INSTALACION',
    sa.Column('INS_Instalacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('INS_Fecha_Instalacion', sa.Date(), nullable=False),
    sa.Column('INS_Estado', sa.Boolean(), nullable=True),
    sa.Column('ACT_Activo', sa.UUID(), nullable=False),
    sa.Column('LIC_Licencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ACT_Activo'], ['INV_ACTIVO.ACT_Activo'], ),
    sa.ForeignKeyConstraint(['LIC_Licencia'], ['INV_LICENCIA.LIC_Licencia'], ),
    sa.PrimaryKeyConstraint('INS_Instalacion')
    )
    op.create_index(op.f('ix_INV_INSTALACION_INS_Instalacion'), 'INV_INSTALACION', ['INS_Instalacion'], unique=False)
    op.create_table('INV_MANTENIMIENTO',
    sa.Column('MAN_Mantenimiento', sa.UUID(), nullable=False),
    sa.Column('MAN_Fecha_Ingreso', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('MAN_Fecha_Cierre', sa.DateTime(), nullable=True),
    sa.Column('MAN_Descripcion_Falla', sa.Text(), nullable=False),
    sa.Column('MAN_Costo_Total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ACT_Activo', sa.UUID(), nullable=False),
    sa.Column('PER_Persona_Solicita', sa.UUID(), nullable=False),
    sa.Column('TMA_Tipo_Mantenimiento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ACT_Activo'], ['INV_ACTIVO.ACT_Activo'], ),
    sa.ForeignKeyConstraint(['PER_Persona_Solicita'], ['INV_PERSONA.PER_Persona'], ),
    sa.ForeignKeyConstraint(['TMA_Tipo_Mantenimiento'], ['INV_TIPO_MANTENIMIENTO.TMA_Tipo_Mantenimiento'], ),
    sa.PrimaryKeyConstraint('MAN_Mantenimiento')
    )
    op.create_index(op.f('ix_INV_MANTENIMIENTO_MAN_Mantenimiento'), 'INV_MANTENIMIENTO', ['MAN_Mantenimiento'], unique=False)
    op.create_table('INV_DETALLE_MANT',
    sa.Column('DMA_Detalle_Mant', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('DMA_Accion_Realizada', sa.String(length=255), nullable=False),
    sa.Column('DMA_Costo_Item', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('MAN_Mantenimiento', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['MAN_Mantenimiento'], ['INV_MANTENIMIENTO.MAN_Mantenimiento'], ),
    sa.PrimaryKeyConstraint('DMA_Detalle_Mant')
    )
    op.create_index(op.f('ix_INV_DETALLE_MANT_DMA_Detalle_Mant'), 'INV_DETALLE_MANT', ['DMA_Detalle_Mant'], unique=False)
    op.create_table('INV_MOVIMIENTO',
    sa.Column('MOV_Movimiento', sa.UUID(), nullable=False),
    sa.Column('MOV_Fecha_Asignacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('MOV_Fecha_Devolucion', sa.DateTime(), nullable=True),
    sa.Column('MOV_Observacion', sa.Text(), nullable=True),
    sa.Column('ACT_Activo', sa.UUID(), nullable=False),
    sa.Column('PER_Persona', sa.UUID(), nullable=False),
    sa.Column('ARE_Area', sa.Integer(), nullable=False),
    sa.Column('TMO_Tipo_Movimiento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ACT_Activo'], ['INV_ACTIVO.ACT_Activo'], ),
    sa.ForeignKeyConstraint(['ARE_Area'], ['INV_AREA.ARE_Area'], ),
    sa.ForeignKeyConstraint(['PER_Persona'], ['INV_PERSONA.PER_Persona'], ),
    sa.ForeignKeyConstraint(['TMO_Tipo_Movimiento'], ['INV_TIPO_MOVIMIENTO.TMO_Tipo_Movimiento'], ),
    sa.PrimaryKeyConstraint('MOV_Movimiento')
    )
    op.create_index(op.f('ix_INV_MOVIMIENTO_MOV_Movimiento'), 'INV_MOVIMIENTO', ['MOV_Movimiento'], unique=False)
    op.create_table('INV_EVIDENCIA',
    sa.Column('EVI_Evidencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EVI_URL_Archivo', sa.String(length=255), nullable=False),
    sa.Column('EVI_Nombre_Archivo', sa.String(length=100), nullable=True),
    sa.Column('EVI_Tipo_MIME', sa.String(length=50), nullable=True),
    sa.Column('MOV_Movimiento_Ref', sa.UUID(), nullable=True),
    sa.Column('MAN_Mantenimiento_Ref', sa.UUID(), nullable=True),
    sa.Column('TEV_Tipo_Evidencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MAN_Mantenimiento_Ref'], ['INV_MANTENIMIENTO.MAN_Mantenimiento'], ),
    sa.ForeignKeyConstraint(['MOV_Movimiento_Ref'], ['INV_MOVIMIENTO.MOV_Movimiento'], ),
    sa.ForeignKeyConstraint(['TEV_Tipo_Evidencia'], ['INV_TIPO_EVIDENCIA.TEV_Tipo_Evidencia'], ),
    sa.PrimaryKeyConstraint('EVI_Evidencia')
    )
    op.create_index(op.f('ix_INV_EVIDENCIA_EVI_Evidencia'), 'INV_EVIDENCIA', ['EVI_Evidencia'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_INV_EVIDENCIA_EVI_Evidencia'), table_name='INV_EVIDENCIA')
    op.drop_table('INV_EVIDENCIA')
    op.drop_index(op.f('ix_INV_MOVIMIENTO_MOV_Movimiento'), table_name='INV_MOVIMIENTO')
    op.drop_table('INV_MOVIMIENTO')
    op.drop_index(op.f('ix_INV_DETALLE_MANT_DMA_Detalle_Mant'), table_name='INV_DETALLE_MANT')
    op.drop_table('INV_DETALLE_MANT')
    op.drop_index(op.f('ix_INV_MANTENIMIENTO_MAN_Mantenimiento'), table_name='INV_MANTENIMIENTO')
    op.drop_table('INV_MANTENIMIENTO')
    op.drop_index(op.f('ix_INV_INSTALACION_INS_Instalacion'), table_name='INV_INSTALACION')
    op.drop_table('INV_INSTALACION')
    op.drop_index(op.f('ix_INV_ESPECIFICACION_ESP_Especificacion'), table_name='INV_ESPECIFICACION')
    op.drop_table('INV_ESPECIFICACION')
    op.drop_index(op.f('ix_INV_AUDITORIA_SISTEMA_AUD_Auditoria'), table_name='INV_AUDITORIA_SISTEMA')
    op.drop_table('INV_AUDITORIA_SISTEMA')
    op.drop_index(op.f('ix_INV_USUARIO_USU_Usuario'), table_name='INV_USUARIO')
    op.drop_index(op.f('ix_INV_USUARIO_USU_Username'), table_name='INV_USUARIO')
    op.drop_table('INV_USUARIO')
    op.drop_index(op.f('ix_INV_ACTIVO_ACT_Codigo_Interno'), table_name='INV_ACTIVO')
    op.drop_index(op.f('ix_INV_ACTIVO_ACT_Activo'), table_name='INV_ACTIVO')
    op.drop_table('INV_ACTIVO')
    op.drop_index(op.f('ix_INV_MODELO_MOD_Modelo'), table_name='INV_MODELO')
    op.drop_table('INV_MODELO')
    op.drop_index(op.f('ix_INV_LICENCIA_LIC_Licencia'), table_name='INV_LICENCIA')
    op.drop_table('INV_LICENCIA')
    op.drop_table('SYS_CONFIGURACION')
    op.drop_index(op.f('ix_INV_TIPO_MOVIMIENTO_TMO_Tipo_Movimiento'), table_name='INV_TIPO_MOVIMIENTO')
    op.drop_table('INV_TIPO_MOVIMIENTO')
    op.drop_index(op.f('ix_INV_TIPO_MANTENIMIENTO_TMA_Tipo_Mantenimiento'), table_name='INV_TIPO_MANTENIMIENTO')
    op.drop_table('INV_TIPO_MANTENIMIENTO')
    op.drop_index(op.f('ix_INV_TIPO_LICENCIA_TLI_Tipo_Licencia'), table_name='INV_TIPO_LICENCIA')
    op.drop_table('INV_TIPO_LICENCIA')
    op.drop_index(op.f('ix_INV_TIPO_EVIDENCIA_TEV_Tipo_Evidencia'), table_name='INV_TIPO_EVIDENCIA')
    op.drop_table('INV_TIPO_EVIDENCIA')
    op.drop_index(op.f('ix_INV_TIPO_ESPECIFICACION_TES_Tipo_Especificacion'), table_name='INV_TIPO_ESPECIFICACION')
    op.drop_table('INV_TIPO_ESPECIFICACION')
    op.drop_index(op.f('ix_INV_TIPO_CONEXION_TCN_Tipo_Conexion'), table_name='INV_TIPO_CONEXION')
    op.drop_table('INV_TIPO_CONEXION')
    op.drop_index(op.f('ix_INV_TIPO_ACTIVO_TAC_Tipo_Activo'), table_name='INV_TIPO_ACTIVO')
    op.drop_table('INV_TIPO_ACTIVO')
    op.drop_index(op.f('ix_INV_SOFTWARE_SOF_Software'), table_name='INV_SOFTWARE')
    op.drop_table('INV_SOFTWARE')
    op.drop_index(op.f('ix_INV_MARCA_MAR_Marca'), table_name='INV_MARCA')
    op.drop_table('INV_MARCA')
    op.drop_index(op.f('ix_INV_ESTADO_OPERATIVO_EOP_Estado_Operativo'), table_name='INV_ESTADO_OPERATIVO')
    op.drop_table('INV_ESTADO_OPERATIVO')
    # ### end Alembic commands ###
