"""agregar_secuencias

Revision ID: e92cb9051d12
Revises: e570198d1dbd
Create Date: 2025-11-27 15:44:14.233258+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92cb9051d12'
down_revision: Union[str, Sequence[str], None] = 'e570198d1dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SYS_SECUENCIA',
    sa.Column('SEC_Secuencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SEC_Contexto', sa.String(length=50), nullable=False),
    sa.Column('SEC_Ultimo_Numero', sa.Integer(), nullable=False),
    sa.Column('SEC_Relleno', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('SEC_Secuencia'),
    sa.UniqueConstraint('SEC_Contexto')
    )
    op.create_index(op.f('ix_SYS_SECUENCIA_SEC_Secuencia'), 'SYS_SECUENCIA', ['SEC_Secuencia'], unique=False)
    op.add_column('INV_TIPO_ACTIVO', sa.Column('TAC_Prefijo', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'INV_TIPO_ACTIVO', ['TAC_Prefijo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'INV_TIPO_ACTIVO', type_='unique')
    op.drop_column('INV_TIPO_ACTIVO', 'TAC_Prefijo')
    op.drop_index(op.f('ix_SYS_SECUENCIA_SEC_Secuencia'), table_name='SYS_SECUENCIA')
    op.drop_table('SYS_SECUENCIA')
    # ### end Alembic commands ###
