"""tablas_organizacion

Revision ID: e9b35c1c4887
Revises: 
Create Date: 2025-11-25 21:31:00.890142+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b35c1c4887'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('INV_CARGO',
    sa.Column('CAR_Cargo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CAR_Nombre', sa.String(length=100), nullable=False),
    sa.Column('CAR_Es_Jefatura', sa.Boolean(), nullable=True),
    sa.Column('CAR_Descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('CAR_Cargo'),
    sa.UniqueConstraint('CAR_Nombre')
    )
    op.create_index(op.f('ix_INV_CARGO_CAR_Cargo'), 'INV_CARGO', ['CAR_Cargo'], unique=False)
    op.create_table('INV_DEPARTAMENTO',
    sa.Column('DEP_Departamento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('DEP_Nombre', sa.String(length=100), nullable=False),
    sa.Column('DEP_Codigo_Costos', sa.String(length=50), nullable=True),
    sa.Column('DEP_Descripcion', sa.String(length=255), nullable=True),
    sa.Column('DEP_Activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('DEP_Departamento'),
    sa.UniqueConstraint('DEP_Nombre')
    )
    op.create_index(op.f('ix_INV_DEPARTAMENTO_DEP_Departamento'), 'INV_DEPARTAMENTO', ['DEP_Departamento'], unique=False)
    op.create_table('INV_PERSONA',
    sa.Column('PER_Persona', sa.UUID(), nullable=False),
    sa.Column('PER_Primer_Nombre', sa.String(length=50), nullable=False),
    sa.Column('PER_Segundo_Nombre', sa.String(length=50), nullable=True),
    sa.Column('PER_Primer_Apellido', sa.String(length=50), nullable=False),
    sa.Column('PER_Segundo_Apellido', sa.String(length=50), nullable=True),
    sa.Column('PER_Email_Corporativo', sa.String(length=150), nullable=False),
    sa.Column('PER_Telefono', sa.String(length=20), nullable=True),
    sa.Column('PER_Estado', sa.Boolean(), nullable=True),
    sa.Column('DEP_Departamento', sa.Integer(), nullable=False),
    sa.Column('CAR_Cargo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['CAR_Cargo'], ['INV_CARGO.CAR_Cargo'], ),
    sa.ForeignKeyConstraint(['DEP_Departamento'], ['INV_DEPARTAMENTO.DEP_Departamento'], ),
    sa.PrimaryKeyConstraint('PER_Persona')
    )
    op.create_index(op.f('ix_INV_PERSONA_PER_Email_Corporativo'), 'INV_PERSONA', ['PER_Email_Corporativo'], unique=True)
    op.create_index(op.f('ix_INV_PERSONA_PER_Persona'), 'INV_PERSONA', ['PER_Persona'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_INV_PERSONA_PER_Persona'), table_name='INV_PERSONA')
    op.drop_index(op.f('ix_INV_PERSONA_PER_Email_Corporativo'), table_name='INV_PERSONA')
    op.drop_table('INV_PERSONA')
    op.drop_index(op.f('ix_INV_DEPARTAMENTO_DEP_Departamento'), table_name='INV_DEPARTAMENTO')
    op.drop_table('INV_DEPARTAMENTO')
    op.drop_index(op.f('ix_INV_CARGO_CAR_Cargo'), table_name='INV_CARGO')
    op.drop_table('INV_CARGO')
    # ### end Alembic commands ###
