"""tablas_geograficas

Revision ID: 8d22c13dbf16
Revises: e9b35c1c4887
Create Date: 2025-11-25 21:37:35.486419+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d22c13dbf16'
down_revision: Union[str, Sequence[str], None] = 'e9b35c1c4887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('INV_PAIS',
    sa.Column('PAI_Pais', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PAI_Nombre', sa.String(length=100), nullable=False),
    sa.Column('PAI_Codigo_ISO', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('PAI_Pais'),
    sa.UniqueConstraint('PAI_Codigo_ISO'),
    sa.UniqueConstraint('PAI_Nombre')
    )
    op.create_index(op.f('ix_INV_PAIS_PAI_Pais'), 'INV_PAIS', ['PAI_Pais'], unique=False)
    op.create_table('INV_ESTADO',
    sa.Column('EST_Estado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EST_Nombre', sa.String(length=100), nullable=False),
    sa.Column('PAI_Pais', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PAI_Pais'], ['INV_PAIS.PAI_Pais'], ),
    sa.PrimaryKeyConstraint('EST_Estado')
    )
    op.create_index(op.f('ix_INV_ESTADO_EST_Estado'), 'INV_ESTADO', ['EST_Estado'], unique=False)
    op.create_table('INV_MUNICIPIO',
    sa.Column('MUN_Municipio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MUN_Nombre', sa.String(length=100), nullable=False),
    sa.Column('EST_Estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EST_Estado'], ['INV_ESTADO.EST_Estado'], ),
    sa.PrimaryKeyConstraint('MUN_Municipio')
    )
    op.create_index(op.f('ix_INV_MUNICIPIO_MUN_Municipio'), 'INV_MUNICIPIO', ['MUN_Municipio'], unique=False)
    op.create_table('INV_SEDE',
    sa.Column('SED_Sede', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SED_Nombre', sa.String(length=150), nullable=False),
    sa.Column('SED_Direccion_Calle', sa.String(length=200), nullable=True),
    sa.Column('SED_Direccion_Numero', sa.String(length=50), nullable=True),
    sa.Column('MUN_Municipio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MUN_Municipio'], ['INV_MUNICIPIO.MUN_Municipio'], ),
    sa.PrimaryKeyConstraint('SED_Sede')
    )
    op.create_index(op.f('ix_INV_SEDE_SED_Sede'), 'INV_SEDE', ['SED_Sede'], unique=False)
    op.create_table('INV_EDIFICIO',
    sa.Column('EDI_Edificio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EDI_Nombre', sa.String(length=100), nullable=False),
    sa.Column('SED_Sede', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['SED_Sede'], ['INV_SEDE.SED_Sede'], ),
    sa.PrimaryKeyConstraint('EDI_Edificio')
    )
    op.create_index(op.f('ix_INV_EDIFICIO_EDI_Edificio'), 'INV_EDIFICIO', ['EDI_Edificio'], unique=False)
    op.create_table('INV_NIVEL',
    sa.Column('NIV_Nivel', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NIV_Numero_Piso', sa.String(length=50), nullable=False),
    sa.Column('NIV_Alias', sa.String(length=100), nullable=True),
    sa.Column('EDI_Edificio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EDI_Edificio'], ['INV_EDIFICIO.EDI_Edificio'], ),
    sa.PrimaryKeyConstraint('NIV_Nivel')
    )
    op.create_index(op.f('ix_INV_NIVEL_NIV_Nivel'), 'INV_NIVEL', ['NIV_Nivel'], unique=False)
    op.create_table('INV_AREA',
    sa.Column('ARE_Area', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ARE_Nombre', sa.String(length=150), nullable=False),
    sa.Column('ARE_Tipo_Acceso', sa.String(length=50), nullable=True),
    sa.Column('ARE_Descripcion', sa.String(length=255), nullable=True),
    sa.Column('NIV_Nivel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NIV_Nivel'], ['INV_NIVEL.NIV_Nivel'], ),
    sa.PrimaryKeyConstraint('ARE_Area')
    )
    op.create_index(op.f('ix_INV_AREA_ARE_Area'), 'INV_AREA', ['ARE_Area'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_INV_AREA_ARE_Area'), table_name='INV_AREA')
    op.drop_table('INV_AREA')
    op.drop_index(op.f('ix_INV_NIVEL_NIV_Nivel'), table_name='INV_NIVEL')
    op.drop_table('INV_NIVEL')
    op.drop_index(op.f('ix_INV_EDIFICIO_EDI_Edificio'), table_name='INV_EDIFICIO')
    op.drop_table('INV_EDIFICIO')
    op.drop_index(op.f('ix_INV_SEDE_SED_Sede'), table_name='INV_SEDE')
    op.drop_table('INV_SEDE')
    op.drop_index(op.f('ix_INV_MUNICIPIO_MUN_Municipio'), table_name='INV_MUNICIPIO')
    op.drop_table('INV_MUNICIPIO')
    op.drop_index(op.f('ix_INV_ESTADO_EST_Estado'), table_name='INV_ESTADO')
    op.drop_table('INV_ESTADO')
    op.drop_index(op.f('ix_INV_PAIS_PAI_Pais'), table_name='INV_PAIS')
    op.drop_table('INV_PAIS')
    # ### end Alembic commands ###
